import { Product, ProductCategory } from './types';

export const productCategories: ProductCategory[] = [
  'all',
  'women-fashion',
  'men-fashion',
  'food',
  'fresh-food',
  'home-interior',
  'electronics',
  'office',
  'daily-goods',
  'beauty',
  'sports',
  'health',
  'baby',
  'kitchen',
  'pets',
  'toys-hobbies',
  'books-music',
];

export const mockProducts: Product[] = [
  {
    id: 'product-fashion-001',
    artist: 'LUMINA',
    category: 'women-fashion',
    delivery: {
      badgeLabel: '오늘 도착',
      fee: 0,
      kind: 'rocket',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80',
    name: 'LUMINA 투어 크롭 티셔츠',
    options: [
      { id: 'size-s', name: 'S', priceDelta: 0 },
      { id: 'size-m', name: 'M', priceDelta: 0 },
      { id: 'size-l', name: 'L', priceDelta: 0 },
    ],
    price: 39000,
    reviewCount: 1842,
    stock: 92,
    tags: ['여성패션', '투어굿즈'],
  },
  {
    id: 'product-fashion-002',
    artist: 'ATEAM',
    category: 'men-fashion',
    delivery: {
      badgeLabel: '내일 도착',
      fee: 0,
      kind: 'rocket',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80',
    name: 'ATEAM 오버핏 후드 집업',
    options: [
      { id: 'size-m', name: 'M', priceDelta: 0 },
      { id: 'size-l', name: 'L', priceDelta: 0 },
      { id: 'size-xl', name: 'XL', priceDelta: 0 },
    ],
    price: 89000,
    reviewCount: 932,
    stock: 25,
    tags: ['남성패션', '후드'],
  },
  {
    id: 'product-food-001',
    artist: '팬덤&',
    category: 'food',
    delivery: {
      badgeLabel: '무료배송',
      fee: 0,
      kind: 'standard',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80',
    name: '콘서트 스낵 박스',
    options: [{ id: 'box-default', name: '기본 세트', priceDelta: 0 }],
    price: 17900,
    reviewCount: 314,
    stock: 140,
    tags: ['식품', '간식'],
  },
  {
    id: 'product-fresh-001',
    artist: '팬덤&',
    category: 'fresh-food',
    delivery: {
      badgeLabel: '오늘 도착',
      fee: 0,
      kind: 'rocket',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&q=80',
    name: '새벽 응원 과일컵 세트',
    options: [{ id: 'fruit-cup-6', name: '6컵', priceDelta: 0 }],
    price: 12900,
    reviewCount: 640,
    stock: 84,
    tags: ['신선식품', '과일'],
  },
  {
    id: 'product-home-001',
    artist: 'NOVA9',
    category: 'home-interior',
    delivery: {
      badgeLabel: '예약배송',
      fee: 3000,
      kind: 'preorder',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=900&q=80',
    name: '포스터 프레임 세트',
    options: [{ id: 'frame-set', name: 'A2 2개입', priceDelta: 0 }],
    price: 29900,
    reviewCount: 87,
    stock: 60,
    tags: ['홈인테리어', '포스터'],
  },
  {
    id: 'product-electronics-001',
    artist: 'LUMINA',
    category: 'electronics',
    delivery: {
      badgeLabel: '오늘 도착',
      fee: 0,
      kind: 'rocket',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80',
    name: '공식 블루투스 응원봉',
    options: [
      { id: 'stick-default', name: '기본 패키지', priceDelta: 0 },
      { id: 'stick-battery', name: '건전지 포함', priceDelta: 2500 },
    ],
    price: 59000,
    reviewCount: 2410,
    stock: 42,
    tags: ['가전디지털', '응원봉'],
  },
  {
    id: 'product-office-001',
    artist: '팬덤&',
    category: 'office',
    delivery: {
      badgeLabel: '내일 도착',
      fee: 0,
      kind: 'rocket',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
    name: '포토카드 슬리브 북 120매',
    options: [{ id: 'binder-120', name: '120매', priceDelta: 0 }],
    price: 15800,
    reviewCount: 1130,
    stock: 260,
    tags: ['문구/오피스', '포토카드'],
  },
  {
    id: 'product-daily-001',
    artist: '팬덤&',
    category: 'daily-goods',
    delivery: {
      badgeLabel: '무료배송',
      fee: 0,
      kind: 'standard',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80',
    name: '굿즈 보관 클리어 박스',
    options: [{ id: 'clear-box', name: '3개입', priceDelta: 0 }],
    price: 22000,
    reviewCount: 498,
    stock: 180,
    tags: ['생활용품', '보관함'],
  },
  {
    id: 'product-beauty-001',
    artist: 'LUMINA',
    category: 'beauty',
    delivery: {
      badgeLabel: '오늘 도착',
      fee: 0,
      kind: 'rocket',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80',
    name: '스테이지 글로우 립틴트',
    options: [
      { id: 'tint-rose', name: '로즈', priceDelta: 0 },
      { id: 'tint-coral', name: '코랄', priceDelta: 0 },
    ],
    price: 14900,
    reviewCount: 970,
    stock: 138,
    tags: ['뷰티', '틴트'],
  },
  {
    id: 'product-sports-001',
    artist: 'NOVA9',
    category: 'sports',
    delivery: {
      badgeLabel: '내일 도착',
      fee: 0,
      kind: 'rocket',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=900&q=80',
    name: '월드투어 피크닉 매트',
    options: [{ id: 'picnic-mat', name: '단품', priceDelta: 0 }],
    price: 28000,
    reviewCount: 266,
    stock: 76,
    tags: ['스포츠/레저', '피크닉'],
  },
  {
    id: 'product-health-001',
    artist: '팬덤&',
    category: 'health',
    delivery: {
      badgeLabel: '무료배송',
      fee: 0,
      kind: 'standard',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80',
    name: '팬미팅 비타민 젤리 30포',
    options: [{ id: 'vitamin-jelly', name: '30포', priceDelta: 0 }],
    price: 19900,
    reviewCount: 352,
    stock: 120,
    tags: ['헬스/건강식품', '비타민'],
  },
  {
    id: 'product-baby-001',
    artist: 'ATEAM',
    category: 'baby',
    delivery: {
      badgeLabel: '내일 도착',
      fee: 0,
      kind: 'rocket',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80',
    name: '키즈 팬 티셔츠 세트',
    options: [
      { id: 'kids-110', name: '110', priceDelta: 0 },
      { id: 'kids-130', name: '130', priceDelta: 0 },
    ],
    price: 26000,
    reviewCount: 144,
    stock: 44,
    tags: ['출산/유아동', '키즈'],
  },
  {
    id: 'product-kitchen-001',
    artist: 'LUMINA',
    category: 'kitchen',
    delivery: {
      badgeLabel: '오늘 도착',
      fee: 0,
      kind: 'rocket',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&w=900&q=80',
    name: '로고 스테인리스 텀블러',
    options: [{ id: 'tumbler-500', name: '500ml', priceDelta: 0 }],
    price: 24000,
    reviewCount: 722,
    stock: 88,
    tags: ['주방용품', '텀블러'],
  },
  {
    id: 'product-pets-001',
    artist: 'NOVA9',
    category: 'pets',
    delivery: {
      badgeLabel: '무료배송',
      fee: 0,
      kind: 'standard',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80',
    name: '펫 응원 케이프',
    options: [
      { id: 'pet-s', name: 'S', priceDelta: 0 },
      { id: 'pet-m', name: 'M', priceDelta: 0 },
    ],
    price: 21000,
    reviewCount: 205,
    stock: 54,
    tags: ['반려동물용품', '케이프'],
  },
  {
    id: 'product-hobby-001',
    artist: 'ATEAM',
    category: 'toys-hobbies',
    delivery: {
      badgeLabel: '예약배송',
      fee: 3000,
      kind: 'preorder',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=900&q=80',
    name: '미니 무대 블록 키트',
    options: [{ id: 'block-kit', name: '단품', priceDelta: 0 }],
    price: 34000,
    reviewCount: 188,
    stock: 31,
    tags: ['완구/취미', '블록'],
  },
  {
    id: 'product-music-001',
    artist: 'NOVA9',
    category: 'books-music',
    delivery: {
      badgeLabel: '내일 도착',
      fee: 0,
      kind: 'rocket',
    },
    imageUrl:
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=80',
    listPrice: 24200,
    name: '미니 4집 포토북반',
    options: [
      { id: 'cover-random', name: '커버 랜덤', priceDelta: 0 },
      { id: 'cover-set', name: '커버 2종 세트', priceDelta: 19800 },
    ],
    price: 21800,
    reviewCount: 1680,
    stock: 128,
    tags: ['도서/음반/DVD', '앨범'],
  },
];

export const featuredProducts = mockProducts.slice(0, 3);
